name: cw_digibyte
description: DigiByte wallet implementation.
version: 0.0.1
publish_to: none
author: Cake Wallet
homepage: https://cakewallet.com

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  cw_core:
    path: ../cw_core
  cw_bitcoin:
    path: ../cw_bitcoin
  hive: ^2.2.3
  path_provider: ^2.0.11
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  intl: ^0.19.0
  shared_preferences: ^2.0.15
  ledger_flutter_plus: ^1.4.1
  ledger_bitcoin:
    git:
      url: https://github.com/cake-tech/ledger-flutter-plus-plugins
      path: packages/ledger-bitcoin
      ref: trunk

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  build_resolvers: ^2.0.9
  mobx_codegen: ^2.0.7
  hive_generator: ^1.1.3

dependency_overrides:
  watcher: ^1.1.0
  protobuf: ^3.1.0
  pointycastle: 3.7.4
  ffi: 2.1.0

flutter:
  uses-material-design: true
