name: cw_digibyte
description: DigiByte wallet implementation.
version: 0.0.1
publish_to: none
author: Cake Wallet
homepage: https://cakewallet.com

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  bip39: ^1.0.6
  flutter:
    sdk: flutter
  cw_core:
    path: ../cw_core
  cw_bitcoin:
    path: ../cw_bitcoin
  hive: ^2.2.3
  path_provider: ^2.0.11
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  intl: ^0.19.0
  shared_preferences: ^2.0.15
  ledger_flutter_plus: ^1.4.1
  ledger_bitcoin:
    git:
      url: https://github.com/cake-tech/ledger-flutter-plus-plugins
      path: packages/ledger-bitcoin
      ref: trunk
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  analyzer: ^7.4.5
  json_serializable: ^6.7.0
